/*
# FLUXORA - Content table and generation limit enforcement

## Overview
Adds the `content` table for storing generated marketing content (TikTok scripts,
hooks, captions, etc.) and a SECURITY DEFINER function that enforces per-plan
generation limits on the backend.

## New Tables

### content
- Stores content generated by each user.
- Owner-scoped via user_id with RLS.
- Fields: product, audience, niche, goal, style, tone, duration, hook,
  on_screen_text, script, visual_structure, cta, caption, hashtags.

## Security

### RLS on content
- 4 separate policies (SELECT/INSERT/UPDATE/DELETE) scoped to auth.uid() = user_id.
- user_id defaults to auth.uid() so inserts work without client passing it.

### check_content_generation_allowed()
- SECURITY DEFINER function that:
  1. Checks if user is admin → unlimited (returns true)
  2. Fetches the user's active subscription and plan
  3. Counts content created in the current billing period
  4. Compares against the plan's content_limit
  5. Returns true if allowed, false if limit reached
- Revoked from anon, granted to authenticated.

## Important Notes
- Admin bypass: admins have unlimited generations (is_admin = true).
- Users without active subscription: no generations allowed.
- The count is based on content rows created in the current period window
  derived from subscription.started_at + plan billing period.
*/
